- name: Pull Nginx Docker Image
  vars:
    ansible_python_interpreter: /bin/python3
  docker_image:
    name: nginx
    source: pull  # Specify the action (pull) to be performed
    state: present  # Ensure the image is present on the host

- name: Run Nginx Container
  vars:
    ansible_python_interpreter: /bin/python3
  docker_container:
    name: nginx-example-docker
    image: nginx
    state: started
    ports:
      - "80:80"
      - "443:443"
